{{ $name := include "rest-api.name" . | printf "%s-hpa" }}
{{ $deploymentName := include "rest-api.name" . | printf "%s-deployment" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deploymentName }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilizationPercentate | default 50 }}

