{{ $name := include "persistent-layer.name" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name | printf "%s-network-policy" }}
spec:
  podSelector:
    matchLabels: {{ printf "app.kubernetes.io/name: %s" $name | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels: 
          access: rest-api 
    - ipBlock:
        cidr: 35.191.0.0/16
    - ipBlock:
        cidr: 130.211.0.0/22
  egress:
  - to:
    - podSelector:
        matchLabels:
          access: rest-api
  policyTypes:
  - Ingress
  - Egress