apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "persistent-layer.name" .) }}
  labels:
    {{- include "persistent-layer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if eq .Values.service.type "ClusterIP"}}
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
  {{- end}}
  ports:
    - port: {{ .Values.port | default 5432 }}
    {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort | default 3001}}
    {{- end}}
      name: postgres-port
  selector:
    {{- include "persistent-layer.selectorLabels" . | nindent 4 }}
