{{ $name := include "web-ui.name" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name | printf "%s-network-policy" }}
spec:
  podSelector:
    matchLabels: {{ printf "app.kubernetes.io/name: %s" $name | nindent 6 }}
  ingress: 
  - {}
  egress:
  - to:
      - podSelector:
          matchLabels:
            access: rest-api
  policyTypes:
  - Ingress
  - Egress