apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-ui.name" . | printf "%s-service" }}
  labels: {{ include "web-ui.selectorLabels" . | nindent 4}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.clusterIPNone }}
  clusterIP: None
  {{- end}}
  selector: {{ include "web-ui.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port | default 3000 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ include "web-ui.name" . | printf "%s-port" }}
      {{- if ne .Values.service.type "ClusterIP" }}
      targetPort: {{ .Values.service.targetPort | default .Values.port 3000 }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort | default 30008}}
      {{- end }}
      {{- end }}