apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ printf "%s-frontend-config" .Values.global.applicationName }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT