# Default values for rest-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/software-containerization-vu/sc-helm/rest-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.4"

imagePullSecrets: []
nameOverride: ""
port: 8000
service:
  nodePort: {}
  targetPort: 8000
  type: NodePort
  clusterIPNone: false

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilizationPercentate: 60

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 250m
    memory: 512M
  requests:
    cpu: 125m
    memory: 256M
